
# reference genome
# where to download assembly
ref_source: http://www.genoscope.cns.fr/externe/plants/data/Boleracea_chromosomes.fasta
# name of reference fasta
ref: data/external/ref/Boleracea_chromosomes.fasta
# dict file for reference assembly
ref_dict: data/external/ref/Boleracea_chromosomes.dict
# annotations for reference assembly
gff_source: http://www.genoscope.cns.fr/externe/plants/data/Boleracea_annotation.gff
# gff file
gff: data/external/ref/Boleracea_annotation.gff
# interval list (if you want to exclude specific regions)
interval_list: data/raw/b_oleracea.interval_list

# FASTQ source
# options: 'SRA' or 'local'
# TODO: add option for 'both'
fastq_source: SRA

# if FASTQ source = SRA
# SRA project info file
# cat SraRunInfo.csv | grep oleracea > Sra_oleracea.csv
# sed -i "1s/^/$(head -n1 SraRunInfo.csv)\n/" Sra_oleracea.csv
sra_info: data/external/Sra_oleracea.csv

# sample and population ids
pop_ids: models/sample_ids.txt

# list of distinguished individuals
distinguished_individuals: models/smc/distinguished_individuals.txt

# directory to use as scratch space
scratch: /scratch/sdturner/

# add paths for locally installed software
# plink2
plink2: ~/software/plink2

# ngsTools (https://github.com/mfumagalli/ngsTools)
ngsTools: ../software/ngsTools

# FINESTRUCTURE software (v4)
# wget https://people.maths.bris.ac.uk/~madjl/finestructure/fs_4.0.1.zip
# unzip fs_4.0.1.zip
finestructure: ../bin/fs_4.0.1

snpable: ../software/seqbility-20091110

# BEAGLE 5.0
beagle: ../software/beagle.11Mar19.69c.jar

# msmc-tools (directory for helper scripts)
msmc_tools: ../software/msmc-tools

# RAiSD 2.0
raisd: ../software/RAiSD

# filtering params
mind: 0.3
